[package]
name = "geometry_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.4.2"
iced_graphics = "0.3.1"
iced_native = "0.5.1"
